# Persistent Volume Claim for PostgreSQL database storage
# Uses EFS storage class for shared, persistent storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  # EFS storage class - unable to test in local K8S cluster.  Comment out before applying locally.
  storageClassName: efs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
